// <auto-generated />
using System;
using FilialBestand.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FilialBestand.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FilialBestand.Domain.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Basiseinheit")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SapProduktNummer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Warengruppe")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("ZuletztSynchronisiert")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SapProduktNummer")
                        .IsUnique();

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("FilialBestand.Domain.Bestand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<int>("FilialeId")
                        .HasColumnType("integer");

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.Property<int>("Mindestbestand")
                        .HasColumnType("integer");

                    b.Property<int>("Zielbestand")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("FilialeId", "ArtikelId")
                        .IsUnique();

                    b.ToTable("Bestaende", t =>
                        {
                            t.HasCheckConstraint("CK_Bestand_Menge", "\"Menge\" >= 0");

                            t.HasCheckConstraint("CK_Bestand_Ziel", "\"Zielbestand\" >= \"Mindestbestand\"");
                        });
                });

            modelBuilder.Entity("FilialBestand.Domain.Filiale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Filialen");
                });

            modelBuilder.Entity("FilialBestand.Domain.Nachbestellvorschlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilialeId")
                        .HasColumnType("integer");

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("FilialeId", "ArtikelId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Offen'");

                    b.ToTable("Nachbestellvorschlaege");
                });

            modelBuilder.Entity("FilialBestand.Domain.Bestand", b =>
                {
                    b.HasOne("FilialBestand.Domain.Artikel", "Artikel")
                        .WithMany("Bestaende")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilialBestand.Domain.Filiale", "Filiale")
                        .WithMany("Bestaende")
                        .HasForeignKey("FilialeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Filiale");
                });

            modelBuilder.Entity("FilialBestand.Domain.Nachbestellvorschlag", b =>
                {
                    b.HasOne("FilialBestand.Domain.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilialBestand.Domain.Filiale", "Filiale")
                        .WithMany()
                        .HasForeignKey("FilialeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Filiale");
                });

            modelBuilder.Entity("FilialBestand.Domain.Artikel", b =>
                {
                    b.Navigation("Bestaende");
                });

            modelBuilder.Entity("FilialBestand.Domain.Filiale", b =>
                {
                    b.Navigation("Bestaende");
                });
#pragma warning restore 612, 618
        }
    }
}
